In [1]:
import numpy as np

## Array creation and initialization  

np.array(): Create an array from a list or tuple.  
np.zeros(): Create an array filled with zeros.  
np.ones(): Create an array filled with ones.  
np.empty(): Create an uninitialized array.  
np.full(): Create an array filled with a specified value.  
np.arange(): Create an array with a range of values.  
np.linspace(): Create an array with linearly spaced values.  
np.logspace(): Create an array with logarithmically spaced values.  
np.eye(): Create an identity matrix.  
np.random.rand(): Create an array with random values uniformly distributed between 0 and 1.  
np.random.randn(): Create an array with random values from a standard normal distribution.  

In [19]:
print("Numpy array with user defined values:")
array=np.array([1,2,3,4])
print(array)

print("\nArray with all zeros: ")
z_arr=np.zeros(2,dtype=np.int_)
print(z_arr)

print("\nArray with all ones: ")
o_arr=np.ones(2,dtype=np.int_)
print(o_arr)

print("\nUninitialized array: ")
e_arr=np.empty(2,dtype=np.float_)
print(e_arr)

print("\nArray filled with ")
f_arr=np.full(10,2)
print(f_arr)

print("\nArray with a range of values: ")
a_arr=np.arange(4,dtype=np.float_)
print(a_arr)

print("\nArray with linearly spaced values:")
ls_arr=np.linspace(1,2,dtype=np.float_)
print(ls_arr)

print("Array with logarithmically spaced values:")
log_arr=np.logspace(19,25,dtype=np.int_)
print(log_arr)

print("Array as an identity matrix:")
i_arr=np.eye(2,3,5)
print(i_arr)

print("Array with random values distributed between 0 and 1:")
r_arr=np.random.rand(4)
print(r_arr)

print("Array having random values from a standard normal distribution:")
rr_arr=np.random.randn(4)
print(rr_arr)





Numpy array with user defined values:
[1 2 3 4]

Array with all zeros: 
[0 0]

Array with all ones: 
[1 1]

Unintialized array: 
[4.24399158e-314 8.48798317e-314]

Array filled with 
[2 2 2 2 2 2 2 2 2 2]

Array with a range of values: 
[0. 1. 2. 3.]

Array with linearly spaced values:
[1.         1.02040816 1.04081633 1.06122449 1.08163265 1.10204082
 1.12244898 1.14285714 1.16326531 1.18367347 1.20408163 1.2244898
 1.24489796 1.26530612 1.28571429 1.30612245 1.32653061 1.34693878
 1.36734694 1.3877551  1.40816327 1.42857143 1.44897959 1.46938776
 1.48979592 1.51020408 1.53061224 1.55102041 1.57142857 1.59183673
 1.6122449  1.63265306 1.65306122 1.67346939 1.69387755 1.71428571
 1.73469388 1.75510204 1.7755102  1.79591837 1.81632653 1.83673469
 1.85714286 1.87755102 1.89795918 1.91836735 1.93877551 1.95918367
 1.97959184 2.        ]
Array with logarithmically spaced values:
[-2147483648 -2147483648 -2147483648 -2147483648 -2147483648 -2147483648
 -2147483648 -2147483648 -2147483648 -2

c:\Users\H.H\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\core\function_base.py:299: RuntimeWarning: invalid value encountered in cast
  return _nx.power(base, y).astype(dtype, copy=False)


## Basic Arithmetic Operations

np.add(), np.subtract(), np.multiply(), np.divide(): Basic arithmetic operations.

In [5]:
array1=np.arange(4,dtype=np.int_).reshape(2,2)

print("First Array: ")
print(array1)

array2=np.array([4,4])

print("\nSecond Array: ")
print(array2)

print("\nAdding two arrays: ")
print(np.add(array1,array2))

print("\nSubtracting two arrays: ")
print(np.subtract(array1,array2))

print("\nMuliplying two ararys: ")
print(np.multiply(array1,array2))

print("\nDividing two arrays: ")
print(np.divide(array1,array2))

First Array: 
[[0 1]
 [2 3]]

Second Array: 
[4 4]

Adding two arrays: 
[[4 5]
 [6 7]]

Subtracting two arrays: 
[[-4 -3]
 [-2 -1]]

Muliplying two ararys: 
[[ 0  4]
 [ 8 12]]

Dividing two arrays: 
[[0.   0.25]
 [0.5  0.75]]


## Reciprocal Function

np.reciprocal(): Return the reciprocal of the elements in an array.

In [7]:
arr1=np.array([19.5,20,1.34,101.9])

print("Original array is: ")
print(arr1)

print("\nArray after reciprocal:")
print(np.reciprocal(arr1))

print("\nAnother array: ")
arr2=np.array([20])
print(arr2)

print("\nAfter applying reciprocal function: ")
print(np.reciprocal(arr2))

Original array is: 
[ 19.5   20.     1.34 101.9 ]

Array after reciprocal:
[0.05128205 0.05       0.74626866 0.00981354]

Another array: 
[20]

After applying reciprocal function: 
[0]


## Power Functions

np.power(): Raise elements of an array to a power.  
np.sqrt(): Compute the square root of each element in an array.  
np.exp(): Calculate the exponential of all elements in the input array.

In [21]:
arr01=np.array([23,19,99])

print("Given Array: ")
print(arr01)

print("\nArray after applying power function: ")
print(np.power(arr01,2))

print("\nSecond array is:")
arr02=np.array([1,2,3])
print(arr02)

print("After applying power function again: ")
print(np.power(arr01,arr02))


print("\nTaking square root of array1: ")
print(np.sqrt(arr01))

print("\nSquare root of array2: ")
print(np.sqrt(arr02))

print("\nComputing exponential of array1 elements:")
print(np.exp(arr01))



Given Array: 
[23 19 99]

Array after applying power function: 
[ 529  361 9801]

Second array is:
[1 2 3]
After applying power function again: 
[    23    361 970299]

Taking square root of array1: 
[4.79583152 4.35889894 9.94987437]

Square root of array2: 
[1.         1.41421356 1.73205081]

Computing exponential of array1 elements:
[9.74480345e+09 1.78482301e+08 9.88903032e+42]


## Mod or Remainder Function

np.mod() and np.remainder(): Return element-wise remainder of division.

In [10]:
arr3=np.array([2,3,6])
arr4=np.array([4,7,13])

print("\nFirst array: ")
print(arr3)

print("\nSecond array: ")
print(arr4)

print("\nAfter applying mod function: ")
print(np.mod(arr3,arr4))

print("\nAfter applying remainder function: ")
print(np.remainder(arr3,arr4))


First array: 
[2 3 6]

Second array: 
[ 4  7 13]

After applying mod function: 
[2 3 6]

After applying remainder function: 
[2 3 6]


## Log Functions

np.log(), np.log10(), np.log2(): Natural, base 10, and base 2 logarithms.

In [23]:
arrr=np.array([2,34,5])

print("\nGiven array:")
print(arrr)

print("\nArray after applying log: ")
print(np.log(arrr))

print("\nArray after applying log10:")
print(np.log10(arrr))

print("\nArray after applying log2:")
print(np.log2(arrr))



Given array:
[ 2 34  5]

Array after applying log: 
[0.69314718 3.52636052 1.60943791]

Array after applying log10:
[0.30103    1.53147892 0.69897   ]

Array after applying log2:
[1.         5.08746284 2.32192809]


## Trignometric & Inverse Trignometric Functions


np.sin(), np.cos(), np.tan(): Trigonometric functions.  
np.arcsin(), np.arccos(), np.arctan(): Inverse trigonometric functions.

In [24]:
array01=np.array([1,2,4,3])

print("\nGiven array:")
print(array01)

print("\nArray after applying Sin function:")
print(np.sin(array01))

print("\nArray after applying Cos function:")
print(np.cos(array01))

print("\nArray after applying Tan function:")
print(np.tan(array01))

print("\nArray after applying Inverse Sin function:")
print(np.arcsin(array01))

print("\nArray after applying Inverse Cos function:")
print(np.arccos(array01))

print("\nArray after applying Inverse Tan function:")
print(np.arctan(array01))



Given array:
[1 2 4 3]

Array after applying Sin function:
[ 0.84147098  0.90929743 -0.7568025   0.14112001]

Array after applying Cos function:
[ 0.54030231 -0.41614684 -0.65364362 -0.9899925 ]

Array after applying Tan function:
[ 1.55740772 -2.18503986  1.15782128 -0.14254654]

Array after applying Inverse Sin function:
[1.57079633        nan        nan        nan]

Array after applying Inverse Cos function:
[ 0. nan nan nan]

Array after applying Inverse Tan function:
[0.78539816 1.10714872 1.32581766 1.24904577]


C:\Users\H.H\AppData\Local\Temp\ipykernel_15540\624673579.py:16: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(array01))
C:\Users\H.H\AppData\Local\Temp\ipykernel_15540\624673579.py:19: RuntimeWarning: invalid value encountered in arccos
  print(np.arccos(array01))


## Hyperbolic & Inverse Hyperbolic Functions

np.sinh(), np.cosh(), np.tanh(): Hyperbolic functions.  
np.arcsinh(), np.arccosh(), np.arctanh(): Inverse hyperbolic functions.

In [25]:
array01=np.array([1,2,4,3])

print("\nGiven array:")
print(array01)

print("\nArray after applying Sinh function:")
print(np.sinh(array01))

print("\nArray after applying Cosh function:")
print(np.cosh(array01))

print("\nArray after applying Tanh function:")
print(np.tanh(array01))

print("\nArray after applying Inverse Sinh function:")
print(np.arcsinh(array01))

print("\nArray after applying Inverse Cosh function:")
print(np.arccosh(array01))

print("\nArray after applying Inverse Tanh function:")
print(np.arctanh(array01))


Given array:
[1 2 4 3]

Array after applying Sinh function:
[ 1.17520119  3.62686041 27.2899172  10.01787493]

Array after applying Cosh function:
[ 1.54308063  3.76219569 27.30823284 10.067662  ]

Array after applying Tanh function:
[0.76159416 0.96402758 0.9993293  0.99505475]

Array after applying Inverse Sinh function:
[0.88137359 1.44363548 2.09471255 1.81844646]

Array after applying Inverse Cosh function:
[0.         1.3169579  2.06343707 1.76274717]

Array after applying Inverse Tanh function:
[inf nan nan nan]


C:\Users\H.H\AppData\Local\Temp\ipykernel_15540\83568105.py:22: RuntimeWarning: divide by zero encountered in arctanh
  print(np.arctanh(array01))
C:\Users\H.H\AppData\Local\Temp\ipykernel_15540\83568105.py:22: RuntimeWarning: invalid value encountered in arctanh
  print(np.arctanh(array01))
