In [2]:
import numpy as np

## Changing Shapes of Arrays

np.reshape(): Change the shape of an array without changing its data.  
np.flatten(): Flatten a multi-dimensional array into a one-dimensional array.  
np.transpose(): Transpose the dimensions of an array.  
np.swapaxes(): Swap two axes of an array.  

In [3]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])

print("\nGiven matrix:")
print(matrix)

print("\nAfter reshaping the given array:")
print(np.reshape(matrix,(3,3)))

print("\nAfter flattening the given array:")
print(matrix.flatten())

print("\nAfter transposing the given array:")
print(np.transpose(matrix))

print("\nAfter swapping two axes of the given:")
print(np.swapaxes(matrix,axis1=0,axis2=1))


Given matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

After reshaping the given array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

After flattening the given array:
[1 2 3 4 5 6 7 8 9]

After transposing the given array:
[[1 4 7]
 [2 5 8]
 [3 6 9]]

After swapping two axes of the given:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


## Concatenate & Copy

np.concatenate(): Join two or more arrays along an axis.  
np.copy(): Return an array copy.  

In [5]:
mat1=np.array([[1,2,3],[4,5,6],[7,8,9]])
mat2=np.array([[9,8,7],[6,5,4],[3,2,1]])

print("\nGiven array 1:")
print(mat1)

print("\nGiven array 2:")
print(mat2)

print("\nGiven array after concatenation:")
print(np.concatenate((mat1,mat2),axis=1))

print("\nCopying given array 1:")
print(np.copy(mat1))


Given array 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Given array 2:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Given array after concatenation:
[[1 2 3 9 8 7]
 [4 5 6 6 5 4]
 [7 8 9 3 2 1]]

Copying given array 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Stacking in Arrays

np.stack(): Stack arrays along a new axis.  
np.hstack(): Stack arrays horizontally (column-wise).  
np.vstack(): Stack arrays vertically (row-wise). 

In [10]:
mat1=np.array([[1,2,3],[4,5,6],[7,8,9]])
mat2=np.array([[9,8,7],[6,5,4],[3,2,1]])

print("\nGiven array 1:")
print(mat1)

print("\nGiven array 2:")
print(mat2)

print("\nArrays after stacking along new axis:")
print(np.stack((mat1,mat2),axis=1))

print("\nArray 1 after stcking horzontally:")
print(np.hstack(mat1))

print("\nArray 1 after stcking vertically:")
print(np.vstack(mat1))



Given array 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Given array 2:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Arrays after stacking along new axis:
[[[1 2 3]
  [9 8 7]]

 [[4 5 6]
  [6 5 4]]

 [[7 8 9]
  [3 2 1]]]

Array 1 after stcking horzontally:
[1 2 3 4 5 6 7 8 9]

Array 1 after stcking vertically:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Array Splitting
 
np.split(): Split an array into multiple sub-arrays.  
np.hsplit(): Split an array horizontally.  
np.vsplit(): Split an array vertically.  


In [23]:
mat1=np.array([[1,2,3],[4,5,6],[7,8,9]])

print("\nGiven array:")
print(mat1)

print("\nGiven array after splitting into sub-arrays:")
print(np.split(mat1,3,axis=0))

print("\nArray after splitting horizontally:")
print(np.hsplit(mat1,3))

print("\nArray after splitting vertically:")
print(np.vsplit(mat1,3))


Given array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Given array after splitting into sub-arrays:
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

Array after splitting horizontally:
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]

Array after splitting vertically:
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
