In [2]:
import numpy as np

## Linear Algebra
np.dot(): Dot product of two arrays.  
np.vdot(): Dot product of two vectors.  
np.inner(): Inner product of two arrays.  
np.outer(): Outer product of two arrays.  
np.matmul(): Matrix product of two arrays.  
np.linalg.inv(): Compute the inverse of a matrix.  
np.linalg.det(): Compute the determinant of a matrix.  
np.linalg.eig(): Compute the eigenvalues and right eigenvectors of a square array.  
np.linalg.svd(): Singular Value Decomposition.  
np.linalg.solve(): Solve a linear matrix equation, or system of linear scalar equations.  
np.linalg.norm(): Matrix or vector norm.  

In [4]:
arr1=np.array([2,5,3,7,9,1])
arr2=np.array([13,22,19,0,5,9])

mat1=np.array([[1,2,3],[4,5,6],[7,8,9]])
mat2=np.array([[9,8,7],[6,5,4],[3,2,1]])
mat3=np.array([[1,2],[3,4]])

print("\nGiven matrix 1:")
print(mat1)

print("\nGiven matrix 2:")
print(mat2)

print("\nDot product of given arrays:")
print(np.dot(arr1,arr2))

print("\nDot product of two vectors:")
print(np.vdot(arr1,arr2))

print("\nInner product of two arrays:")
print(np.inner(arr1,arr2))

print("\nOuter product of two arrays:")
print(np.outer(arr1,arr2))

print("\nMatrix product of two arrays:")
print(np.matmul(mat1,mat2))

print("\nInverse of the given matrix 1:")
print(np.linalg.inv(mat3))



Given matrix 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Given matrix 2:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Dot product of given arrays:
247

Dot product of two vectors:
247

Inner product of two arrays:
247

Outer product of two arrays:
[[ 26  44  38   0  10  18]
 [ 65 110  95   0  25  45]
 [ 39  66  57   0  15  27]
 [ 91 154 133   0  35  63]
 [117 198 171   0  45  81]
 [ 13  22  19   0   5   9]]

Matrix product of two arrays:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Inverse of the given matrix 1:
[[-2.   1. ]
 [ 1.5 -0.5]]
